### ISSUE TITLE
Something is wrong when use niftymic_run_reconstruction_pipeline 

### ISSUE THREAD

**Issue by sunlianglong** [gift-surg/NiftyMIC#10]
Hi renbem,
when I used the command 'niftymic_run_reconstruction_pipeline ' , there were something wrong in the last step to reconstruct a srr_template_mask in template space. I could't sovle it.😭 I used the docker and pull your image.

The log prompt me that the motion_correction file is missing, but I have repeatedly confirmed that the file is in the current directory, or in the srr20 directory, everything is complete. All files are accessible with permission.

niftymic_reconstruct_volume_from_slices \
> --filenames 'FetusNEWLIUYING_seg.nii.gz' 'FetusNEWLIUYINGA_seg.nii.gz' 'FetusNEWLIUYINGB_seg.nii.gz' \
> --dir-input-mc 'srr22/recon_template_space/motion_correction' \
> --output 'srr22/recon_template_space/srr_template_mask.nii.gz' \
> --reconstruction-space 'srr22/recon_template_space/srr_template.nii.gz' \
> --suffix-mask '' \
> --log-config 1 \
> --mask \
> --sda \
> --alpha 1

***************************************************************************************************
*** Configuration: ***
--- alpha: 1.0
--- config: None
--- data_loss: linear
--- data_loss_scale: 1
--- dir_input_mc: srr22/recon_template_space/motion_correction
--- extra_frame_target: 10
--- filenames: 
	FetusNEWLIUYING_seg.nii.gz
	FetusNEWLIUYINGA_seg.nii.gz
	FetusNEWLIUYINGB_seg.nii.gz
--- filenames_masks: None
--- intensity_correction: 1
--- isotropic_resolution: None
--- iter_max: 10
--- iterations: 15
--- log_config: 1
--- mask: True
--- minimizer: lsmr
--- output: srr22/recon_template_space/srr_template_mask.nii.gz
--- pd_alg_type: ALG2
--- reconstruction_space: srr22/recon_template_space/srr_template.nii.gz
--- reconstruction_type: TK1L2
--- rho: 0.1
--- sda: True
--- slice_thicknesses: None
--- suffix_mask: 
--- target_stack: None
--- tv_solver: PD
--- use_masks_srr: 0
--- verbose: 0
--- viewer: itksnap

NiftyMIC version: 0.7.5
***************************************************************************************************

--- File written to 'srr22/recon_template_space/config_reconstruct_volume_from_slices_20200625-142804.json'.

***************************************************************************************************
*** Read Data ***
--- Stack 'FetusNEWLIUYING_seg': Slice positions updated (15/15 slices deleted)
--- Stack 'FetusNEWLIUYING_seg' removed as all slices were deleted
--- Stack 'FetusNEWLIUYINGA_seg': Slice positions updated (15/15 slices deleted)
--- Stack 'FetusNEWLIUYINGA_seg' removed as all slices were deleted
--- Stack 'FetusNEWLIUYINGB_seg': Slice positions updated (19/19 slices deleted)
--- Stack 'FetusNEWLIUYINGB_seg' removed as all slices were deleted
Traceback (most recent call last):
  File "/usr/local/bin/niftymic_reconstruct_volume_from_slices", line 11, in <module>
    load_entry_point('NiftyMIC', 'console_scripts', 'niftymic_reconstruct_volume_from_slices')()
  File "/app/NiftyMIC/niftymic/application/reconstruct_volume_from_slices.py", line 127, in main
    data_reader.read_data()
  File "/app/NiftyMIC/niftymic/base/data_reader.py", line 286, in read_data
    motion_updater.run()
  File "/app/NiftyMIC/niftymic/utilities/motion_updater.py", line 225, in run
    "All stacks removed. "
RuntimeError: All stacks removed. Did you check that the correct motion-correction directory was provided?

**Comment by renbem** [comment]
Hi sunlianglong,

You seemed to have chosen a different structure than was outlined [here](https://github.com/gift-surg/NiftyMIC#automatic-segmentation-and-high-resolution-reconstruction-of-fetal-brain-mri). 

To generate a 3D SRR of the mask volume, NiftyMIC needs to associate the obtained motion-correction transformations for image files with the segmentation mask files. The default assumption is that images and masks have the same filenames but are split into two different folders, e.g. `nifti` and `seg`. However, in your case, segmentation files have the suffix `_seg` which therefore needs to be provided as an input parameter, i.e. `--suffix-mask _seg`. From what I can see, that should work for you then.

**Comment by sunlianglong** [comment]
Yes, It works! Thank you for your prompt reply.
