### ISSUE TITLE
MONAI-based fetal brain segmentation pipeline

### ISSUE THREAD

**Issue by martaranzini** [gift-surg/NiftyMIC#11]
A new sub-module will be included in the package to perform the automated segmentation of brain in fetal MRI.
This module will be developed using the MONAI framework (https://monai.io/) and will provide:

- [ ] A new pretrained model that improves the performance of the currently used one
- [ ] The associated python script to run inference with the provided model
- [ ] Utilities to (re-)train the segmentation model to ease the introduction and use of model updates within the package.

**Comment by renbem** [comment]
Part of NiftyMIC v0.8 since f4432f18f02de55f1f61265d83219566dccf655c
