### ISSUE TITLE
Readme  auto reconstruction error

### ISSUE THREAD

**Issue by Achillesy** [gift-surg/NiftyMIC#14]
niftymic_run_reconstruction_pipeline \
--filenames \
nifti/name-of-stack-1.nii.gz \
nifti/name-of-stack-2.nii.gz \
nifti/name-of-stack-N.nii.gz \
--filenames-masks \
seg/name-of-stack-1.nii.gz \
seg/name-of-stack-2.nii.gz \
seg/name-of-stack-N.nii.gz \
--dir-output srr

This command does not work. There is no --filenames-masks or --dir-output anymore. I tried this:
niftymic_run_reconstruction_pipeline \
--filenames \
nifti/name-of-stack-1.nii.gz \
seg/name-of-stack-1.nii.gz \
--output srr/name-of-stack-1.nii.gz

This works, but there is no benefit of reconstruction. Maybe I should run it three times and use the xyz direction output to reconstruct it?

**Comment by renbem** [comment]
Could you please provide a terminal print-out with additional system/environment information to document this behaviour?

**Comment by Achillesy** [comment]
```
(py3venv) niftymic@virtualbox [02/18/21 20:47:20]: /home/niftymic/Software/NiftyMIC git:(master) 
➜   python niftymic_run_reconstruction_pipeline.py 
Traceback (most recent call last):
  File "niftymic_run_reconstruction_pipeline.py", line 4, in <module>
    from niftymic.application.multiply_stack_with_mask import main
ModuleNotFoundError: No module named 'niftymic.application.multiply_stack_with_mask'
```

after modified line 4 to 
from niftymic.application.multiply import main

```
➜   python niftymic_run_reconstruction_pipeline.py -h
usage: niftymic_run_reconstruction_pipeline.py [-h] [--config CONFIG]
                                               --filenames FILENAMES
                                               [FILENAMES ...] --output OUTPUT
                                               [--verbose VERBOSE]

Multiply images. Pixel type is determined by first given image. Args that
start with '--' (eg. --dir-output) can also be set in a config file (specified
via --config). If an arg is specified in more than one place, then commandline
values override config file values which override defaults.

optional arguments:
  -h, --help            show this help message and exit
  --config CONFIG       Configuration file in JSON format.
  --filenames FILENAMES [FILENAMES ...]
                        Paths to NIfTI file images (nii.gz, or nii).
  --output OUTPUT       Path to output image file (nii.gz, or nii).
  --verbose VERBOSE     Turn on/off verbose output. [default: 0]

Author: Michael Ebner (michael.ebner.14@ucl.ac.uk)
```

The result after I run the command:
https://github.com/Achillesy/Python_FetalMRI/tree/master/srr

I am not sure how to optimize the results next.

_A small suggestion, it would be better if you add an English(US) keyboard to the virtual machine Input Source.  I'm so confused when I input '~' or '@'.  _  :)

That you for your help.

**Comment by renbem** [comment]
Please do not make any changes to the code yourself to "fix" something. So, after you have reverted to the original, can you just run `niftymic_run_reconstruction_pipeline -h`? I.e. without the `python` etc before

**Comment by Achillesy** [comment]
1. delete virtual machine "Ubuntu 18.04" with files.
2. import from file "Ubuntu1804_v0.7.1_20190330.ova"
3. change vboxshare folder
4. run virtual machine
5. 
```
(py3venv) niftymic@virtualbox [02/18/21 22:46:49]: /home/niftymic/Software/NiftyMIC git:(master) 
➜   python niftymic_run_reconstruction_pipeline.py -h
Traceback (most recent call last):
  File "niftymic_run_reconstruction_pipeline.py", line 4, in <module>
    from niftymic.application.multiply_stack_with_mask import main
ModuleNotFoundError: No module named 'niftymic.application.multiply_stack_with_mask'
```
I'm sorry.

**Comment by renbem** [comment]
As indicated above, please run `niftymic_run_recunstruction_pipeline -h` instead of `python niftymic_run_recunstruction_pipeline.py -h`. You can run the first command from any directory (as long as py3venv is active)

**Comment by Achillesy** [comment]
v8.0 works fine! That's awesome!
Thank you very much.
