### ISSUE TITLE
2D or 3D bias field correction in preprocessing step ?

### ISSUE THREAD

**Issue by alexpron** [gift-surg/NiftyMIC#16]
Dear all,

Thank you for this great package. I was wondering if the N4 bias field correction in the preprocessing step was a 3D one performed on the stack volume or a 2D one performed slice by slice. 
Have a great day
Alex

**Comment by renbem** [comment]
Hi Alex,
Happy to hear NiftyMIC is useful to you. Its [N4 bias field correction step](https://github.com/gift-surg/NiftyMIC/blob/e62c5389dfa2bb367fb217b7060472978d3e7654/niftymic/utilities/n4_bias_field_correction.py#L63) is based on the SimpleITK's version of [N4BiasFieldCorrectionImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1N4BiasFieldCorrectionImageFilter.html#details). By default, 3D processing is performed.
