### ISSUE TITLE
Order or stacks

### ISSUE THREAD

**Issue by ajdneuro12** [gift-surg/NiftyMIC#17]
Hello, 

Thanks for this great tool. Do the stacks have to be in a certain order according to acquisition. I am getting the error that there is not enough correspondence between stack02 and stack 01 or stack02 and stack04 for the rigid registration. Thanks!

Best,
Alex

**Comment by renbem** [comment]
Hi Alex,
No particular order is required. It's important to pick the 'target stack' to cover the entire/sufficient anatomical region of interest so that other stacks (which might cover less) can be registered to it.
Best,
Michael
