### ISSUE TITLE
Exception even when launching NiftyMIC commands without input

### ISSUE THREAD

**Issue by zappst** [gift-surg/NiftyMIC#18]
Hi there, 

I get the following errors even when launching simply (for instance) _niftymic_reconstruct_volume_: 

niftymic_reconstruct_volume_from_slices
itkStreamingProcessObject not found in module ITKCommon because of exception:
 'module' object has no attribute 'itkStreamingProcessObject'
itkMultiThreaderBase not found in module ITKCommon because of exception:
 'module' object has no attribute 'itkMultiThreaderBase'
itkPoolMultiThreader not found in module ITKCommon because of exception:
 'module' object has no attribute 'itkPoolMultiThreader'
itkPlatformMultiThreader not found in module ITKCommon because of exception:
 'module' object has no attribute 'itkPlatformMultiThreader'
itkVectorContainerULSS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkVectorContainerULSS'
vectoritkImageRGBUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageRGBUC2'
vectoritkImageRGBAUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageRGBAUC2'
vectoritkImageVF22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVF22'
vectoritkImageVF32 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVF32'
vectoritkImageVF42 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVF42'
vectoritkImageCVF22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVF22'
vectoritkImageCVF32 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVF32'
vectoritkImageCVF42 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVF42'
vectoritkImageSS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageSS2'
vectoritkImageUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageUC2'
vectoritkImageUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageUS2'
vectoritkImageF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageF2'
vectoritkImageCF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCF2'
vectoritkImageVD22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD22'
vectoritkImageVD32 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD32'
vectoritkImageVD42 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD42'
vectoritkImageD2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageD2'
vectoritkImageUL2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageUL2'
vectoritkImageULL2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageULL2'
vectoritkImageB2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageB2'
vectoritkImageFAF22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageFAF22'
vectoritkImageO22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageO22'
vectoritkImageSSRTD22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageSSRTD22'
vectoritkImageRGBUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageRGBUC3'
vectoritkImageRGBAUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageRGBAUC3'
vectoritkImageVF23 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVF23'
vectoritkImageVF33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVF33'
vectoritkImageVF43 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVF43'
vectoritkImageCVF23 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVF23'
vectoritkImageCVF33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVF33'
vectoritkImageCVF43 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVF43'
vectoritkImageSS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageSS3'
vectoritkImageUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageUC3'
vectoritkImageUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageUS3'
vectoritkImageF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageF3'
vectoritkImageCF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCF3'
vectoritkImageVD23 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD23'
vectoritkImageVD33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD33'
vectoritkImageVD43 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD43'
vectoritkImageD3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageD3'
vectoritkImageUL3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageUL3'
vectoritkImageULL3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageULL3'
vectoritkImageB3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageB3'
vectoritkImageFAF33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageFAF33'
vectoritkImageO33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageO33'
vectoritkImageSSRTD33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageSSRTD33'
vectoritkImageVF12 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVF12'
vectoritkImageVD24 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD24'
vectoritkImageVD34 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD34'
vectoritkImageVD44 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVD44'
vectoritkImageVF13 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageVF13'
vectoritkImageCVD22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVD22'
vectoritkImageCVD32 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVD32'
vectoritkImageCVD42 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVD42'
vectoritkImageCVD23 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVD23'
vectoritkImageCVD33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVD33'
vectoritkImageCVD43 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'vectoritkImageCVD43'
itkImageToImageFilterISS2ICF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterISS2ICF2'
itkImageToImageFilterISS3ICF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterISS3ICF3'
itkImageToImageFilterIUC2ICF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterIUC2ICF2'
itkImageToImageFilterIUC3ICF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterIUC3ICF3'
itkImageToImageFilterIUS2ICF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterIUS2ICF2'
itkImageToImageFilterIUS3ICF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterIUS3ICF3'
itkImageToImageFilterICF2ISS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterICF2ISS2'
itkImageToImageFilterICF3ISS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterICF3ISS3'
itkImageToImageFilterICF2IUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterICF2IUC2'
itkImageToImageFilterICF3IUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterICF3IUC3'
itkImageToImageFilterICF2IUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterICF2IUS2'
itkImageToImageFilterICF3IUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterICF3IUS3'
itkImageToImageFilterISSRTD22ISSRTD22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterISSRTD22ISSRTD22'
itkImageToImageFilterISSRTD33ISSRTD33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageToImageFilterISSRTD33ISSRTD33'
itkInPlaceImageFilterIRGBUC2ISS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIRGBUC2ISS2'
itkInPlaceImageFilterIRGBUC3ISS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIRGBUC3ISS3'
itkInPlaceImageFilterIRGBUC2IUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIRGBUC2IUS2'
itkInPlaceImageFilterIRGBUC3IUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIRGBUC3IUS3'
itkInPlaceImageFilterIRGBUC2IF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIRGBUC2IF2'
itkInPlaceImageFilterIRGBUC3IF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIRGBUC3IF3'
itkInPlaceImageFilterISS2ICF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterISS2ICF2'
itkInPlaceImageFilterISS3ICF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterISS3ICF3'
itkInPlaceImageFilterIUC2ICF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIUC2ICF2'
itkInPlaceImageFilterIUC3ICF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIUC3ICF3'
itkInPlaceImageFilterIUS2ICF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIUS2ICF2'
itkInPlaceImageFilterIUS3ICF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterIUS3ICF3'
itkInPlaceImageFilterICF2ISS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterICF2ISS2'
itkInPlaceImageFilterICF3ISS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterICF3ISS3'
itkInPlaceImageFilterICF2IUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterICF2IUC2'
itkInPlaceImageFilterICF3IUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterICF3IUC3'
itkInPlaceImageFilterICF2IUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterICF2IUS2'
itkInPlaceImageFilterICF3IUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkInPlaceImageFilterICF3IUS3'
itkDefaultDynamicMeshTraitsSS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsSS2'
itkDefaultDynamicMeshTraitsSS22SSSS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsSS22SSSS'
itkDefaultDynamicMeshTraitsSS22SSSSSS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsSS22SSSSSS'
itkDefaultDynamicMeshTraitsUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUC2'
itkDefaultDynamicMeshTraitsUC22UCUC not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUC22UCUC'
itkDefaultDynamicMeshTraitsUC22UCUCUC not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUC22UCUCUC'
itkDefaultDynamicMeshTraitsUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUS2'
itkDefaultDynamicMeshTraitsUS22USUS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUS22USUS'
itkDefaultDynamicMeshTraitsUS22USUSUS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUS22USUSUS'
itkDefaultDynamicMeshTraitsF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsF2'
itkDefaultDynamicMeshTraitsD2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsD2'
itkDefaultDynamicMeshTraitsSS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsSS3'
itkDefaultDynamicMeshTraitsSS33SSSS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsSS33SSSS'
itkDefaultDynamicMeshTraitsSS33SSSSSS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsSS33SSSSSS'
itkDefaultDynamicMeshTraitsUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUC3'
itkDefaultDynamicMeshTraitsUC33UCUC not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUC33UCUC'
itkDefaultDynamicMeshTraitsUC33UCUCUC not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUC33UCUCUC'
itkDefaultDynamicMeshTraitsUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUS3'
itkDefaultDynamicMeshTraitsUS33USUS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUS33USUS'
itkDefaultDynamicMeshTraitsUS33USUSUS not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsUS33USUSUS'
itkDefaultDynamicMeshTraitsF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsF3'
itkDefaultDynamicMeshTraitsD3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultDynamicMeshTraitsD3'
itkDefaultStaticMeshTraitsSS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsSS2'
itkDefaultStaticMeshTraitsUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsUC2'
itkDefaultStaticMeshTraitsUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsUS2'
itkDefaultStaticMeshTraitsF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsF2'
itkDefaultStaticMeshTraitsD2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsD2'
itkDefaultStaticMeshTraitsSS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsSS3'
itkDefaultStaticMeshTraitsUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsUC3'
itkDefaultStaticMeshTraitsUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsUS3'
itkDefaultStaticMeshTraitsF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsF3'
itkDefaultStaticMeshTraitsD3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkDefaultStaticMeshTraitsD3'
itkImageDuplicatorISSRTD22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageDuplicatorISSRTD22'
itkImageDuplicatorISSRTD33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageDuplicatorISSRTD33'
itkImageSinkIRGBUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIRGBUC2'
itkImageSinkIRGBUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIRGBUC3'
itkImageSinkIRGBAUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIRGBAUC2'
itkImageSinkIRGBAUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIRGBAUC3'
itkImageSinkIVF22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIVF22'
itkImageSinkIVF23 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIVF23'
itkImageSinkIVF32 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIVF32'
itkImageSinkIVF33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIVF33'
itkImageSinkIVF42 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIVF42'
itkImageSinkIVF43 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIVF43'
itkImageSinkICVF22 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkICVF22'
itkImageSinkICVF23 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkICVF23'
itkImageSinkICVF32 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkICVF32'
itkImageSinkICVF33 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkICVF33'
itkImageSinkICVF42 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkICVF42'
itkImageSinkICVF43 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkICVF43'
itkImageSinkISS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkISS2'
itkImageSinkISS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkISS3'
itkImageSinkIUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIUC2'
itkImageSinkIUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIUC3'
itkImageSinkIUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIUS2'
itkImageSinkIUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIUS3'
itkImageSinkIF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIF2'
itkImageSinkIF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkIF3'
itkImageSinkICF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkICF2'
itkImageSinkICF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkICF3'
itkImageSinkVISS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkVISS2'
itkImageSinkVIUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkVIUC2'
itkImageSinkVIUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkVIUS2'
itkImageSinkVIF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkVIF2'
itkImageSinkVISS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkVISS3'
itkImageSinkVIUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkVIUC3'
itkImageSinkVIUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkVIUS3'
itkImageSinkVIF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkImageSinkVIF3'
itkNumericTraitsCF not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkNumericTraitsCF'
itkPointSetSS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetSS2'
itkPointSetUC2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetUC2'
itkPointSetUS2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetUS2'
itkPointSetF2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetF2'
itkPointSetD2 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetD2'
itkPointSetSS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetSS3'
itkPointSetUC3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetUC3'
itkPointSetUS3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetUS3'
itkPointSetF3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetF3'
itkPointSetD3 not loaded from module ITKCommon because of exception:
 'module' object has no attribute 'itkPointSetD3'
Traceback (most recent call last):
  File "/usr/local/bin/niftymic_reconstruct_volume_from_slices", line 11, in <module>
    load_entry_point('NiftyMIC', 'console_scripts', 'niftymic_reconstruct_volume_from_slices')()
  File "/home/zappst/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/zappst/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/zappst/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/zappst/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/zappst/NiftyMIC-master/niftymic/application/reconstruct_volume_from_slices.py", line 21, in <module>
    import niftymic.reconstruction.admm_solver as admm
  File "/home/zappst/NiftyMIC-master/niftymic/reconstruction/admm_solver.py", line 19, in <module>
    from niftymic.reconstruction.solver import Solver
  File "/home/zappst/NiftyMIC-master/niftymic/reconstruction/solver.py", line 21, in <module>
    import niftymic.reconstruction.linear_operators as lin_op
  File "/home/zappst/NiftyMIC-master/niftymic/reconstruction/linear_operators.py", line 26, in <module>
    class LinearOperators(object):
  File "/home/zappst/NiftyMIC-master/niftymic/reconstruction/linear_operators.py", line 48, in LinearOperators
    image_type=itk.Image.D3,
  File "/home/zappst/.local/lib/python2.7/site-packages/itkLazy.py", line 52, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "/home/zappst/.local/lib/python2.7/site-packages/itkBase.py", line 214, in LoadModule
    namespace[snakeCaseFunction] = getattr(module, snakeCaseFunction)
AttributeError: 'module' object has no attribute 'image_to_image_filter'

I tried to reinstall it. All requirements are met and all prerequisites from the GitHub website.
I was wondering what else I can try.

Many thanks,
Stefano.

**Comment by renbem** [comment]
Looks like ITK was not properly installed. Can you confirm you went through the steps as outlined in the specific [ITK_NiftyMIC Installation Wiki](https://github.com/gift-surg/ITK_NiftyMIC/wiki#compilation) and its inclusion within python works? See the associated [Usage](https://github.com/gift-surg/ITK_NiftyMIC/wiki#usage) for more details.

**Comment by zappst** [comment]
Hi Michael,

Thank you for the prompt response.
Yes, I did, without though cleaning folders and path.

I was wondering, what would be the best way to uninstall ITK_NiftyMIC in a clean way to try to install it brand new?

**Comment by renbem** [comment]
You can just remove the build folder. Just make sure you have plenty of coffee next to you; building it from source will take a while ...

**Comment by zappst** [comment]
Hi Michael,

Thank you for your help so far.

I have installed ITK_NiftyMIC from scratch. Unfortunately, I still have the same problem.
When I execute:

> import itk
> print(itk.Image.D3.New())

then the same error as before is thrown. Interestingly, if I run _> print(itk.Image.D3.New())_ again, the command seems to work. Then the problem is with the following command _> print(itk.OrientedGaussianInterpolateImageFilter.ID3ID3.New())_.

It seems like it is caused by an improper installation of itk_NiftyMIC or a broken pointer from python to the itk_NiftyMIC.

Any suggestion on what to try next would be more than appreciated.

Many thanks,
Stefano.

**Comment by renbem** [comment]
Hi,
Can you please confirm that:

- no itk python libraries are installed in the first place prior to your installation (e.g. via pip install itk). I'd indeed recommend using a fresh virtual machine for installing NiftyMIC.
- [ITK_NiftyMIC](https://github.com/gift-surg/ITK_NiftyMIC/wiki) is installed as described. It's indeed important to use this repo since standard ITK does not come with OrientedGaussianInterpolateImageFilter (and others we added)
- the [compilation](https://github.com/gift-surg/ITK_NiftyMIC/wiki#compilation) and [inking](https://github.com/gift-surg/ITK_NiftyMIC/wiki#linking) steps were completed successfully.

Once the compilation of ITK_NiftyMIC was done successfully (which is the most elaborate step of the installation) then all subsequent steps should be rather straightforward.

**Comment by zappst** [comment]
Dear Michael,

Thank you for your prompt support.

The problem was given by a different version of ITK installed in the machine and then by an old version of python (2.7 I believe).
Using a virtual environment (very straightforward guide: https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) and installing everything with pip3 fixed the problems.

I imagine now I have to activate the python virtual environment every time I need to run NiftyMIC?

Again, thank you for your support.

Cheers,
Stefano.
