### ISSUE TITLE
PermissionError with Docker image

### ISSUE THREAD

**Issue by lillepeder** [gift-surg/NiftyMIC#19]
Please feel free to delete this if this is the wrong place to post this.

**The goal:** Want to combine an axial and saggital volume into a single high res volume.

**The issue:** Permission error when running the docker image.

Traceback (most recent call last):
  File "/usr/local/bin/niftymic_reconstruct_volume_from_slices", line 11, in <module>
    load_entry_point('NiftyMIC', 'console_scripts', 'niftymic_reconstruct_volume_from_slices')()
  File "/app/NiftyMIC/niftymic/application/reconstruct_volume_from_slices.py", line 106, in main
    input_parser.log_config(os.path.abspath(__file__))
  File "/app/NiftyMIC/niftymic/utilities/input_arparser.py", line 170, in log_config
    ph.write_dictionary_to_json(dic, path_to_config_file, verbose=True)
  File "/usr/local/lib/python3.6/site-packages/pysitk/python_helper.py", line 1691, in write_dictionary_to_json
    with open(path_to_file, access_mode) as fp:
PermissionError: [Errno 13] Permission denied: 'config_reconstruct_volume_from_slices_20220103-090401.json'

**The command:**
`docker run -ti --rm -u $(id -u) -v $(pwd -P)/data -v $(pwd -P)/results renbem/niftymic niftymic_reconstruct_volume_from_slices --filenames ax.nii.gz sag.nii.gz --filenames-masks ax_mask.nii.gz sag_mask.nii.gz --output srr.nii.gz`

I have tried to change the command various ways to no avail. For instance, omitting the `-u` flag throws the strange output.

***************************************************************************************************

--- File written to 'config_reconstruct_volume_from_slices_20220103-091200.json'.

***************************************************************************************************
*** Read Data ***
Traceback (most recent call last):
  File "/usr/local/bin/niftymic_reconstruct_volume_from_slices", line 11, in <module>
    load_entry_point('NiftyMIC', 'console_scripts', 'niftymic_reconstruct_volume_from_slices')()
  File "/app/NiftyMIC/niftymic/application/reconstruct_volume_from_slices.py", line 127, in main
    data_reader.read_data()
  File "/app/NiftyMIC/niftymic/base/data_reader.py", line 271, in read_data
    extract_slices=self._extract_slices,
  File "/app/NiftyMIC/niftymic/base/stack.py", line 60, in from_filename
    raise exceptions.FileNotExistent(file_path)
niftymic.base.exceptions.FileNotExistent: File 'ax.nii.gz' does not exist

The file `ax.nii.gz` does indeed exist in the `data` dir specificed with `-v`.

Am I missing something obvious?

**Comment by renbem** [comment]
Hi, can you try the following?
```
docker run --rm -ti -v path-to-your-directory:/shared-folder --user $(id -u):$(id -g) renbem/niftymic
```

**Comment by lillepeder** [comment]
Running that literal line of code does put me into some interactive mode. Prefix `I have no name!@f00e6e107a31:/app$`.

Editing my above command with the edited `--user` flag produces the same error.

**Comment by renbem** [comment]
"Not having a name" shouldn't cause an issue and typically works. I have not worked with Docker in a while, so not sure whether there is a better way. In any case, there may be is an issue with the way you provide the volumes to access your data. Can you try providing a single volume and run niftymic in interactive mode as suggested above? This should work (at least it has done so on other instances)

**Comment by lillepeder** [comment]
I will give this a shot, thanks for the quick feedback!

**Comment by lillepeder** [comment]
This turned out to work! Thank you very much for helping a newbie out!
