### ISSUE TITLE
Output image for registration saved in Temporary files

### ISSUE THREAD

**Issue by Aureleane** [gift-surg/NiftyMIC#21]
Hello, 

I have started using Niftymic very recently, more precisely the registration. 
The output file given contains the transformation. The transformed image itself, which is the one I need, was a bit harder to find, as it is sent to the temporary files. I was wondering if it would be possible to implement a solution to choose in which file to send the registered image instead of the transformation.

Thanks !

**Comment by renbem** [comment]
Hi Aureleane, can you describe in a bit more detail which registration you refer to and what application/executable you are using?

**Comment by renbem** [comment]
If you refer to niftymic_register_image, then this is on purpose. The temporary output is a resampled version of the SRR to the reference grid (e.g. template space). However, to prevent the resampling from affecting the image quality, a subsequent SRR step with updated transformations in reference space (e.g. template space) is recommended. See [here](https://github.com/gift-surg/NiftyMIC#srr-methods-for-motion-corrected-or-static-data) for the follow-up steps.

**Comment by Aureleane** [comment]
Hello Renbem, 

Thank you for your answer. 
I am indeed using niftymic_register_image, to register an SRR outcome (from niftymic_reconstruct_volume) to a template so it can have the same anatomical space. 
I am not sure I understand the subsequent SRR steps with the update transformations. Is it niftymic_reconstruct_volume_from_slices that has to be appplied to the output images of the registration?

**Comment by renbem** [comment]
Hi,
That's correct, niftymic_reconstruct_volume_from_slices needs to be applied with a pointer to transformations as described [here](https://github.com/gift-surg/NiftyMIC#srr-from-motion-corrected-or-static-slice-acquisitions). You could also run all steps automatically based on the information provided [here](https://github.com/gift-surg/NiftyMIC#automatic-reconstruction).

**Comment by Aureleane** [comment]
Great, thanks. The first option worked.

**Comment by renbem** [comment]
Great. I'm glad to hear.
