### ISSUE TITLE
Motion simulation

### ISSUE THREAD

**Issue by malaifa** [gift-surg/NiftyMIC#23]
Hi, great work! Which is the motion simulation code.

**Comment by renbem** [comment]
Hi Malaifa, I am unsure what you refer to. NiftyMIC was developed to perform motion correction + SRR. However, there is a [motion_simulator class](https://github.com/gift-surg/NiftyMIC/blob/master/niftymic/validation/motion_simulator.py), which may be useful for whatever purpose you have in mind.

**Comment by renbem** [comment]
Closing now since I haven't heard back. Let me know if there is any additional question on this.

**Comment by malaifa** [comment]
Thank you very much for your reply. I want to simulate the motion corrupted stacks of 2D slices, because I already have the SR images. 
Thanks!
