### ISSUE TITLE
The volume "filesystem root" has only X bytes disk space remaining

### ISSUE THREAD

**Issue by federica28** [gift-surg/NiftyMIC#3]
I installed NiftyMIC as vm on VirtualBox two months ago and i used it since that moment without any major problem. However in this last week i got this warning:
### ** "The volume "filesystem root" has only X bytes disk space remaining".**
Now i have 0 bytes disk space remaining and i can't elaborate any images.

Executing the following command i obtain: 

<img width="313" alt="df -h" src="https://user-images.githubusercontent.com/44544961/57138066-f515db00-6db1-11e9-9ee8-2f3da2010360.PNG">

What can i do?

**Comment by renbem** [comment]
Dear Frederica,

Let me know if I misinterpret this, but, by the looks of it, I would assume that all NiftyMIC results were created within the virtual machine and not on the host system side.
Within the VM you have access to your host system storage on /media/vboxshare (shown to have 248 GB available), which is the recommended place to store the reconstruction output of NiftyMIC.

Hope that helps.

Best,
Michael

**Comment by federica28** [comment]
Hi Michael,
I have always saved the reconstruction output of NiftyMIC in /media/vboxshare, not in folders within the virtual machine.

Best,
Federica

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by renbem** [comment]
Hi Frederica,

I can't quite tell from here what has cluttered your root directory. If I look at a VM clone, there is plenty of space available (7.8 GB).
![image](https://user-images.githubusercontent.com/11680758/57161483-a5e89e00-6de3-11e9-9278-d43e8873d030.png)

Do you restart your VM once in a while? It might well be that some intermediate results in the /tmp - folder cause the issue. Other than that, NiftyMIC does not write anything to your local HDD.
If that's not the problem, a straightforward way to re-establish a clutter-free VM (without having to run an investigation of what the additional files are) is to import a fresh VM download.

Best,
Michael
