### ISSUE TITLE
Enquiry about the NiftyMIC commands

### ISSUE THREAD

**Issue by sahas111** [gift-surg/NiftyMIC#6]
Hi, I have included two reconstructed images here from our highly motion corrupted 2D T2-HASTE slices. I compared the images with BTK generated ones. I reconstructed those outputs in two steps:
1. niftymic_reconstruct_volume \
--filenames path-to-stack1.nii.gz ... path-to-stackN.nii.gz \
--filenames-masks path-to-stack1_mask.nii.gz ... path-to-stackN_mask.nii.gz \
--output path-to-srr.nii.gz \

2. niftymic_reconstruct_volume_from_slices \
--filenames path-to-stack1.nii.gz ... path-to-stackN.nii.gz \
--dir-input-mc dir-to-motion_correction \
--output path-to-srr.nii.gz \
--reconstruction-type HuberL2 \
--alpha 0.003
I used the brain+badslice mask for the first step.

![Picture2](https://user-images.githubusercontent.com/10149107/67773137-f301b000-faa6-11e9-81ff-5f3bf6eecab9.png)
![Picture1](https://user-images.githubusercontent.com/10149107/67773138-f301b000-faa6-11e9-9966-e21e6950da72.png)

For both of the data, by qualitative observation the reconstruction is not optimal. Do you have any suggestion or explanation for that? We actually intend to publish our study soon.

**Comment by renbem** [comment]
Hi,
Difficult to tell without more information on the input data. To me, it seems that the default assumption of slice thickness equals pixel spacing is incorrect. Do you acquire your stacks with overlap? If that's the case, please provide the slice thickness using --slice-thicknesses.
Best,
Michael

**Comment by renbem** [comment]
@sahas111, has this solved the issue for you?
