### ISSUE TITLE
Update to make it work with Boost 1.70

### ISSUE THREAD

**Issue by luiscarlosgph** [gift-surg/NiftyMIC#7]

**Comment by luiscarlosgph** [comment]
diff --git a/niftymic/cli/CMakeLists.txt b/niftymic/cli/CMakeLists.txt
index 99d1267..742710f 100644
--- a/niftymic/cli/CMakeLists.txt
+++ b/niftymic/cli/CMakeLists.txt
@@ -29,6 +29,7 @@ find_package(Boost COMPONENTS program_options REQUIRED)

 include_directories(${Boost_INCLUDE_DIRS})
 link_directories(${Boost_LIBRARY_DIRS})
+set (Boost_LIBRARIES "${Boost_LIBRARIES} -lboost_program_options")

**Comment by renbem** [comment]
Thanks for info and help. To aovid potential other clashes, I have refactored some of the code so that the Boost dependency is now obsolete since daad8dd589db65614aeb74bc09086f8d1d9ebaec.
