### ISSUE TITLE
Reconstruction in the subject space crashes unexpectedly

### ISSUE THREAD

**Issue by LucasFidon** [gift-surg/NiftyMIC#8]
I have observed regularly that the reconstruction in subject space crashes unexpectedly.
Typically several warnings from fslorient appear and shortly after the program crashes during the first volume-to-volume registration (see below for an example of logs associated with the problem).

Monitoring the memory in some cases for which it happens, I think the program stops due to a Memory Error.

There is maybe not much that can be done to prevent the memory error except using a machine with more memory. However, NiftyMIC should state the memory error correctly. The current logs are inaccurate and confusing.

I will try to investigate how to catch this memory error.

Example of logs associated with this problem:
*** 12/12 -- UZL00181/Study1 ***
['t2_haste_body_sag_24.nii.gz', 't2_haste_brain_ax_9.nii.gz', 't2_haste_brain_cor_10.nii.gz', 't2_haste_brain_cor_12.nii.gz', 't2_haste_brain_cor_14.nii.gz', 't2_haste_brain_cor_16.nii.gz', 't2_haste_brain_cor_18.nii.gz', 't2_haste_brain_cor_19.nii.gz', 't2_haste_brain_sag_11.nii.gz', 't2_haste_uterus_2.nii.gz']
--- Searching for suitable target stack ... done
--- File written to '/home/lucasf/workspace/giftcloudsrr/src/target_stacks.json'.

---- Executed command: ----
niftymic_run_reconstruction_pipeline \
--filenames /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_body_sag_24.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_ax_9.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_10.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_12.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_14.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_16.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_18.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_19.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_sag_11.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_uterus_2.nii.gz \
--filenames-masks /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_body_sag_24.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_ax_9.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_10.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_12.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_14.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_16.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_18.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_19.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_sag_11.nii.gz /home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_uterus_2.nii.gz \
--dir-output /home/lucasf/data/giftcloudsrr/UZL00181/Study1/srr \
--bias-field-correction 0 \
--target-stack /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_18.nii.gz \
--run-bias-field-correction 0 \
--run-recon-subject-space 1 \
--run-recon-template-space 0 \
--run-diagnostics 0 \
--verbose 1 \
--log-config 1 \
--threshold 0.800000
---------------------------

***************************************************************************************************
*** Configuration: ***
--- alpha: 0.01
--- automatic_target_stack: 1
--- bias_field_correction: 0
--- config: None
--- dir_output: /home/lucasf/data/giftcloudsrr/UZL00181/Study1/srr
--- filenames:
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_body_sag_24.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_ax_9.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_10.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_12.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_14.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_16.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_18.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_19.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_sag_11.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_uterus_2.nii.gz
--- filenames_masks:
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_body_sag_24.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_ax_9.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_10.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_12.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_14.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_16.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_18.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_19.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_sag_11.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_uterus_2.nii.gz
--- initial_transform: None
--- intensity_correction: 1
--- interleave: 3
--- isotropic_resolution: None
--- iter_max: 10
--- log_config: 1
--- multiresolution: 0
--- outlier_rejection: 1
--- prefix_output: srr_
--- reference: None
--- reference_mask: None
--- run_bias_field_correction: 0
--- run_diagnostics: 0
--- run_recon_subject_space: 1
--- run_recon_template_space: 0
--- s2v_hierarchical: False
--- sda: False
--- search_angle: 180
--- slice_thicknesses: None
--- suffix_mask:
--- target_stack: /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_18.nii.gz
--- template: None
--- template_mask: None
--- threshold: 0.8
--- threshold_first: 0.5
--- two_step_cycles: 3
--- v2v_robust: False
--- verbose: 1

NiftyMIC version: 0.7.4
***************************************************************************************************

--- File written to '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/srr/config_run_reconstruction_pipeline_20200107-092104.json'.

---- Executed command: ----
niftymic_reconstruct_volume \
--filenames '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_body_sag_24.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_ax_9.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_10.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_12.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_14.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_16.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_18.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_19.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_sag_11.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_uterus_2.nii.gz' \
--filenames-masks '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_body_sag_24.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_ax_9.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_10.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_12.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_14.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_16.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_18.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_19.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_sag_11.nii.gz' '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_uterus_2.nii.gz' \
--multiresolution 0 \
--target-stack '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_18.nii.gz' \
--output '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/srr/recon_subject_space/srr_subject.nii.gz' \
--suffix-mask '' \
--intensity-correction 1 \
--alpha 0.01 \
--iter-max 10 \
--two-step-cycles 3 \
--outlier-rejection 1 \
--threshold-first 0.500000 \
--threshold 0.800000 \
--verbose 1 \
--log-config 1 \
--isotropic-resolution 0.800000
---------------------------

WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

***************************************************************************************************
*** Configuration: ***
--- alpha: 0.01
--- alpha_first: 0.2
--- bias_field_correction: 0
--- boundary_stacks:
10
10
0
--- config: None
--- dilation_radius: 3
--- extra_frame_target: 10
--- filenames:
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_body_sag_24.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_ax_9.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_10.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_12.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_14.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_16.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_18.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_19.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_sag_11.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_uterus_2.nii.gz
--- filenames_masks:
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_body_sag_24.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_ax_9.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_10.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_12.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_14.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_16.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_18.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_cor_19.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_brain_sag_11.nii.gz
/home/lucasf/data/giftcloudsrr/UZL00181/Study1/seg/t2_haste_uterus_2.nii.gz
--- intensity_correction: 1
--- interleave: 3
--- isotropic_resolution: 0.8
--- iter_max: 10
--- iter_max_first: 5
--- iterations: 15
--- log_config: 1
--- metric: Correlation
--- metric_radius: 10
--- multiresolution: 0
--- outlier_rejection: 1
--- output: /home/lucasf/data/giftcloudsrr/UZL00181/Study1/srr/recon_subject_space/srr_subject.nii.gz
--- reconstruction_type: TK1L2
--- reference: None
--- reference_mask: None
--- s2v_hierarchical: False
--- sda: False
--- search_angle: 45
--- shrink_factors:
3
2
1
--- sigma: 1
--- slice_thicknesses: None
--- smoothing_sigmas:
1.5
1
0
--- subfolder_motion_correction: motion_correction
--- suffix_mask:
--- target_stack: /home/lucasf/data/giftcloudsrr/UZL00181/Study1/nifti/t2_haste_brain_cor_18.nii.gz
--- threshold: 0.8
--- threshold_first: 0.5
--- transforms_history: 0
--- two_step_cycles: 3
--- use_masks_srr: 0
--- v2v_method: RegAladin
--- v2v_robust: False
--- verbose: 1
--- viewer: itksnap
--- write_motion_correction: 1

NiftyMIC version: 0.7.4
***************************************************************************************************
--- File written to '/home/lucasf/data/giftcloudsrr/UZL00181/Study1/srr/recon_subject_space/config_reconstruct_volume_20200107-092106.json'.

***************************************************************************************************
*** Read Data ***
--- 10 input stacks read for further processing

***************************************************************************************************
*** Data Preprocessing ***
--- 10 stacks were loaded for data preprocessing
--- Crop stacks to their masks

***************************************************************************************************
*** Volume-to-Volume Registration ***
--- Volume-to-Volume Registration -- Stack 1/10

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--- WARNING: Only q-form is set as fslorient was not successful!
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--- WARNING: Only q-form is set as fslorient was not successful!
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--- WARNING: Only q-form is set as fslorient was not successful!
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--- WARNING: Only q-form is set as fslorient was not successful!
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

200107-09:21:19,618 nipype.interface WARNING:
version_from_command member of CommandLine was Deprecated in nipype-1.0.0 and deleted in 1.1.0
Traceback (most recent call last):
  File "/home/lucasf/workspace/srr/bin/niftymic_reconstruct_volume", line 11, in <module>
    load_entry_point('NiftyMIC==0.7.4', 'console_scripts', 'niftymic_reconstruct_volume')()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/niftymic/application/reconstruct_volume.py", line 260, in main
    v2vreg.run()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/niftymic/utilities/volumetric_reconstruction_pipeline.py", line 65, in run
    self._run()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/niftymic/utilities/volumetric_reconstruction_pipeline.py", line 171, in _run
    self._registration_method.run()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/niftymic/registration/registration_method.py", line 169, in run
    self._run()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/niftymic/registration/niftyreg.py", line 97, in _run
    self._registration_method.run()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/simplereg/simple_itk_registration_base.py", line 245, in run
    self._run()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/simplereg/niftyreg.py", line 124, in _run
    nreg = nipype.interfaces.niftyreg.RegAladin()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/nipype/interfaces/niftyreg/base.py", line 58, in __init__
    _version = self.version_from_command()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 747, in version_from_command
    stderr=sp.PIPE,
  File "/home/lf18/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/lf18/anaconda3/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/home/lucasf/workspace/srr/bin/niftymic_run_reconstruction_pipeline", line 11, in <module>
    load_entry_point('NiftyMIC==0.7.4', 'console_scripts', 'niftymic_run_reconstruction_pipeline')()
  File "/home/lucasf/workspace/srr/lib/python3.7/site-packages/niftymic/application/run_reconstruction_pipeline.py", line 295, in main
    raise RuntimeError("Reconstruction in subject space failed")
RuntimeError: Reconstruction in subject space failed

**Comment by renbem** [comment]
Thanks for the detailed description of the problem. It indeed seems to be associated with a memory problem as indicated also by `OSError: [Errno 12] Cannot allocate memory` in the print out.

Could you provide information about whether increasing your swap space has solved the problem? On my test system, I have about 16 GB for both memory and swap space.

**Comment by renbem** [comment]
Since the problem seems to be related to the local computational resources, I am closing this issue now. Please reopen if needed.
