### ISSUE TITLE
Running tests/installation_test.py occurs an error about c3d

### ISSUE THREAD

**Issue by onyxiakylin** [gift-surg/NiftyMIC#9]
Hi, I'm running the installation_test.py after installing all dependencies. However, there reports an error which seems to be related to c3d and I don't know how to solve it.

python -m nose tests/installation_test.py
E..

ERROR: test_fsl (tests.installation_test.InstallationTest)

Traceback (most recent call last):
  File "/home/mwj/NiftyMIC/tests/installation_test.py", line 41, in test_fsl
    registration_method.run()
  File "/home/mwj/NiftyMIC/niftymic/registration/registration_method.py", line 169, in run
    self._run()
  File "/home/mwj/NiftyMIC/niftymic/registration/flirt.py", line 101, in _run
    self._registration_method.run()
  File "/home/mwj/anaconda3/lib/python3.7/site-packages/simplereg/simple_itk_registration_base.py", line 245, in run
    self._run()
  File "/home/mwj/anaconda3/lib/python3.7/site-packages/simplereg/flirt.py", line 101, in _run
    self._registration_transform_sitk = self._convert_to_sitk_transform()
  File "/home/mwj/anaconda3/lib/python3.7/site-packages/simplereg/flirt.py", line 120, in _convert_to_sitk_transform
    verbose=self._verbose,
  File "/home/mwj/anaconda3/lib/python3.7/site-packages/simplereg/flirt_to_simpleitk_converter.py", line 54, in convert_flirt_to_sitk_transform
    c3d.run()
  File "/home/mwj/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/home/mwj/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/home/mwj/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
c3d_affine_tool -ref /tmp/tmpc32c_pa9/FLIRT/fixed.nii.gz -src /tmp/tmpc32c_pa9/FLIRT/moving.nii.gz /tmp/tmpc32c_pa9/FLIRT/registration_transform.txt -fsl2ras -oitk /tmp/tmpc32c_pa9/FLIRT/registration_transform_sitk.txt
Standard output:

Standard error:
terminate called after throwing an instance of 'char const*'
Aborted (core dumped)
Return code: 134
...
...
...

Ran 3 tests in 18.550s

FAILED (errors=1)"

**Comment by renbem** [comment]
Hi,
Could you provide some more information on which version of [Convert3D](http://www.itksnap.org/pmwiki/pmwiki.php?n=Downloads.C3D) was installed?
Also, after you ran the test command, can you try to run the printed command, i.e. 
```
c3d_affine_tool -ref /tmp/tmpc32c_pa9/FLIRT/fixed.nii.gz -src /tmp/tmpc32c_pa9/FLIRT/moving.nii.gz /tmp/tmpc32c_pa9/FLIRT/registration_transform.txt -fsl2ras -oitk /tmp/tmpc32c_pa9/FLIRT/registration_transform_sitk.txt
```
above, in a separate terminal to see whether this works?

**Comment by onyxiakylin** [comment]
Hi, thanks to your instant reply and my c3d version is 1.0.0 whose filename is "c3d-1.0.0-Linux-x86_64.tar.gz".
And I have run the printed command after running the test command just now. It also report the sentence：

`c3d_affine_tool` -ref /tmp/tmpc32c_pa9/FLIRT/fixed.nii.gz -src /tmp/tmpc32c_pa9/FLIRT/moving.nii.gz /tmp/tmpc32c_pa9/FLIRT/registration_transform.txt -fsl2ras -oitk `/tmp/tmpc32c_pa9/FLIRT/registration_transform_sitk.txt`
terminate called after throwing an instance of 'char const*'
Abandoned (core dumped)

I think maybe it processed a null pointer.  However, when I open the /tmp to look the content of "registration_transform_sitk.txt" , it said as follow, 

0x1.ffdb6688dfa58p-1  -0x1.f1a1796240a9fp-7  0x1.28b715401fc27p-6  0x1.da112bd02a0cp-4  
0x1.f8fdc9f9a202p-7  0x1.ffe679c5b28c2p-1  -0x1.94008a0be42dap-7  -0x1.006c3ec274972p-1  
-0x1.2596f4aa2f3ep-6  0x1.9d08e11243bbfp-7  0x1.ffe08aacf1ab3p-1  0x1.6359203ae996cp-3  
0x0p+0  0x0p+0  0x0p+0  0x1p+0 

So the result content means what,  successfully or failed conversion?

**Comment by renbem** [comment]
That's interesting. Could it be because you use Python 3.7? Can you check what happens in case of Python 3.6 is used (tested version)?

**Comment by onyxiakylin** [comment]
I used Python 3.5 to test but it also occurred the situation.  However, I utilized the software to get some reconstruction results. So as I suspected before, this may not have much effect on normal use, at least for now.
Anyway, if there is any problem, I will report it later. Thanks for your reply.

**Comment by renbem** [comment]
By default, `RegAladin` is used for the volume-to-volume registration steps. However, given that both `FLIRT` and `RegAladin` build on a similar `nipype` wrapping here, I am a little surprised that the error does not occur when `RegAladin` is used. 

For future reference, could you please provide the output for `registration_transform.txt` too? Since this file is used to obtain `registration_transform_sitk.txt` as shown above this could provide good insight.

**Comment by onyxiakylin** [comment]
Excuse me for seeing the reply late. And of course, I will send you the whole tmp files. I ran again to generate files. Hope it will be a little bit useful. 
[tmp6zma495c.zip](https://github.com/gift-surg/NiftyMIC/files/4214902/tmp6zma495c.zip)

**Comment by renbem** [comment]
Thanks for that. It indeed shows that the output transformation `registration_transform.txt` of `FLIRT` is corrupted but not the one associated with `RegAladin`. I can't quite tell from here why that is the case. Since both of them build on `Nipype` the remaining thing I can think of asking from here now is to see whether there is some issue with a more recent `nipype` version. Which version do you use? I have `nipype==1.2.0` installed.

Sorry for the problem you experience but thank you for your patience in this.

**Comment by onyxiakylin** [comment]
My nipype version is 1.4.1, but I think it's not the reason causing the error. Anyway, the normal reconstruction can be accomplished by the program.

So let's leave it at that and if there's a derivative problem because of that, I'll report back to you at that time. (It's working fine now at least.)

Also thank you for following up my question and patient reply.
